[package]
name = "Find_brain"
version = "0.3.0"
edition = "2021"

[dependencies]
libloading = "0.8.1"
lazy_static = "1.4.0"
once_cell = "1.19.0"

rustils="0.1.23"

#цветной вывод в консоль
console = "0.15.7"

#для блума
#bloomfilter = "1"
#bincode = "1.3.3"
#serde = { version = "1.0.197", features = ["derive"] }
#serde_json = "1.0.114"

hex = "0.4.3"
base58 = "0.2.0"

sha2 = "0.11.0-pre.3"
crypto-hash ="0.3.4"

sv = "0.2.2"
tokio = { version = "1.37.0", features = ["rt", "rt-multi-thread", "macros"] }
itertools = "0.13.0"
num_cpus = "1.16.0"
rand = "0.8.5"

secp256k1 = { version = "0.29.0", features = ["rand"] }

#это нужно для иконки в винде
[target.'cfg(windows)'.build-dependencies]
winres = "0.1.12"