[package]
name = "Find_brain"
version = "0.0.6"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libloading = "0.8.1"
libc = { version = "0.2.149", features = [] }

rustils="0.1.23"

#цветной вывод в консоль
console = "0.15.7"

#для блума
bloomfilter = "1"
bincode = "1.3.3"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"

hex = "0.4.3"
base58 = "0.2.0"

sha2 = "0.11.0-pre.3"

sv = "0.2.2"
tokio = { version = "1.36.0", features = ["rt", "rt-multi-thread", "macros"] }
itertools = "0.12.1"
num_cpus = "1.16.0"


#это нужно для иконки
[target.'cfg(windows)'.build-dependencies]
winres = "0.1.12"